[target.aarch64-linux-android]
linker = "clang"
rustflags = [
  "-C",
  "link-arg=/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/archlinux/usr/local/bin/mold",
]

[source.crates-io]
replace-with = 'rsproxy-sparse'
[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"
[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"
[registries.rsproxy]
index = "https://rsproxy.cn/crates.io-index"
[net]
git-fetch-with-cli = true
